name: Deploy snapshot with Maven

on:
  push:
    branches-ignore:
      - production
      - development
  pull_request:
    types:
      - opened
      - edited
    branches-ignore:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17.0.7
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.7'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify